Repository Bjornar97/Bachelor-Interaktivt-Kart, pull requests merged in 2019-02, with the labels that each got.

#9 Restructuring
  .vscode/launch.json
  .vscode/settings.json
  KartApp/src/app.css
  KartApp/src/app/account-page/account-page-routing.module.ts
  KartApp/src/app/account-page/account-page.component.css
  KartApp/src/app/account-page/account-page.component.html
  KartApp/src/app/account-page/account-page.component.ts
  KartApp/src/app/account-page/account-page.module.ts
  KartApp/src/app/app-routing.module.ts
  KartApp/src/app/app.component.html
  KartApp/src/app/app.component.ts
  KartApp/src/app/app.module.ts
  KartApp/src/app/home-page/home-page-routing.module.ts
  KartApp/src/app/home-page/home-page.component.css
  KartApp/src/app/home-page/home-page.component.html
  KartApp/src/app/home-page/home-page.component.ts
  KartApp/src/app/home-page/home-page.module.ts
  KartApp/src/app/home/home.component.html
  KartApp/src/app/map-page/map-page.component.html
  KartApp/src/app/map-page/map-page.component.ts
  KartApp/src/app/map-page/map-page.module.ts
  KartApp/src/app/map/map.component.css
  KartApp/src/app/map/map.component.html
  KartApp/src/app/map/map.component.ts
Labels: Testet-Android, enhancement

#18 Dra opp tingen
  KartApp/src/app.css
  KartApp/src/app/app.component.html
  KartApp/src/app/app.component.ts
Labels: Testet-Android, enhancement

#22 Kart
  KartApp/package-lock.json
  KartApp/package.json
  KartApp/src/app.css
  KartApp/src/app/app.component.html
  KartApp/src/app/app.component.ts
  KartApp/src/app/app.module.ts
  KartApp/src/app/globals.ts
  KartApp/src/app/home-page/home-page.component.html
  KartApp/src/app/home-page/home-page.component.ts
  KartApp/src/app/location.ts
  KartApp/src/app/map/map.component.html
  KartApp/src/app/map/map.component.ts
  KartApp/src/app/tracker.ts
Labels: New Feature, Testet-Android

#27 Innstillinger
  KartApp/package-lock.json
  KartApp/package.json
  KartApp/src/app/app-routing.module.ts
  KartApp/src/app/app.component.ts
  KartApp/src/app/app.module.ts
  KartApp/src/app/globals.ts
  KartApp/src/app/map/map.component.ts
  KartApp/src/app/settings-page/map-menu/map-menu.component.css
  KartApp/src/app/settings-page/map-menu/map-menu.component.html
  KartApp/src/app/settings-page/map-menu/map-menu.component.ts
  KartApp/src/app/settings-page/settings-page-routing.module.ts
  KartApp/src/app/settings-page/settings-page.component.css
  KartApp/src/app/settings-page/settings-page.component.html
  KartApp/src/app/settings-page/settings-page.component.ts
  KartApp/src/app/settings-page/settings-page.module.ts
  KartApp/src/app/settings-page/settings.service.spec.ts
  KartApp/src/app/settings-page/settings.service.ts
Labels: Testet-Android

#30 iOS bug fix
  KartApp/package.json
  KartApp/src/app.css
  KartApp/src/app/account-page/account-page.component.html
  KartApp/src/app/app.component.html
  KartApp/src/app/home-page/home-page.component.html
  KartApp/src/app/settings-page/settings-page.component.html
  KartApp/src/app/settings-page/settings.service.spec.ts
Labels: Testet-Android, Testet-iOS, iOS

#32 iOS bug fix kartfix
  KartApp/src/app/app.component.html
Labels: Testet-Android, Testet-iOS

#33 Dra opp tingen forbedret kartknapper
  KartApp/src/app.css
  KartApp/src/app/app.component.html
  KartApp/src/app/app.component.ts
Labels: Testet-Android, Testet-iOS
